### PR TITLE
Rewrite 2022

### LINKED ISSUE #1: Implement Presence
Presence class is currently just an empty stub. It should be implemented with tests based on the JS client.

### LINKED ISSUE #4: Socket automatic recovery
how important is this ?

### LINKED ISSUE #19: "phx_join" is never sent if socket is not open by the time `Join` is called
Creating a channel and immediately joining it will cause the "phx_join" message to be stuck in `Channel`'s sendBuffer forever, if the underlying WebSocket is not open by the time `Join` is called.

Example code:
```
var fooChannel = _socket.MakeChannel("foo");
fooChannel.Join(new Dictionary<string, object>(), _timeout)
```

The second line will eventually call `Socket.Push(Message)`. That method will check if the channel's socket is already in state `Open`. If it isn't, it will return `false` which will cause its calling method, `Channel.Push(Push, TimeSpan?)`, to add the "phx_join" message to its `sendBuffer`. But `FlushSendBuffer` is only called in `OnJoinReply`. So it can't ever be sent and the channel will never be joined.

### PR DESCRIPTION
**Pull request by Mazyod**
Attempt to rewrite to match new PhoenixJS implementation.

Fixes #1 
Fixes #4 
Fixes #19 

## TODO

- [x] Implement Presence
- [x] Add Presence tests
- [x] Consider async/await API
- [x] Check automatic error recovery functionality (!closeWasClean && code != 1_000)
- [x] Test on actual Unity project
- [x] Add more helpers / utils (cp script, BestHTTP adapter, Delayed Executor, …)
- [x] Update readme and migration process (vsn 2.0.0 serialization)

## Background

This library was initially written back in 2017 or something, when I had a lot more free time on my hands. I had refactored a lot of bits and written them differently than how they were implemented on Phoenix JS.

Now in 2022, Phoenix JS is much more mature and stable implementation, and using it as a reference implementation will help support the maintainability of this project (I hope!). This also unlocks benefits of new Phoenix JS features to be easily migrated almost line by line.

As much as any developer out there, I dislike breaking changes. However, after 5 years, this library is due for one big rewrite to restructure the internals better, and upgrade the syntax for a new C# language version as supported by Unity. Not to mention, I think I learned a thing or two in those five years, so the code should be of higher quality and performance, generally speaking. Finally, it should also be .NET Core compatible for portability and CI support for tests and coverage.

Regardless, I haven't seen what other developers in the OSS community out there have put out during this time. So if anyone know of a better library that solves the problem this project hopes to address, please share.

### CODE REVIEW

**Comment by Mazyod** [comment]
This PR is failing the integration tests at the very last step...
Once that is also hopefully resolved, will migrate tests from PhoenixJS as well to make sure this rewrite doesn't cause more problems than it solves.

**Comment by Mazyod** [comment]
🟢

**Comment by Mazyod** [comment]
Fixes #19

**Comment by arne-schroppe** [comment]
I tried to test this branch in our Unity project (we're using Unity 2021.2.7f1 at the moment) but couldn't get it to compile. Initially we had just dropped the source code into our project (I don't quite remember why we did this maybe it was easier or there was a dependency issue). That didn't work anymore now because Unity didn't have `Systems.Collections.Immutable`. 

Then I tried building PhoenixSharp as a dll and using that in our project, but now the entire `Phoenix` namespace can't be found and the project doesn't compile. What is strange is that the inspector for the dll says "Targets .NET 4.x" when it is clearly built for .net 5.0. Maybe Unity's support for .net 5.0 is a bit shaky? I am not sure and need to investigate more when I have more time. 

It would be interesting to hear how you use this in Unity and whether you saw similar issues.

**Comment by Mazyod** [comment]
Thanks for the feedback, @arne-schroppe !

I didn't get a chance to reach the "Test on actual Unity project" checkbox, so I didn't get a chance to take a look at the possible issues 😅 .. I do plan to make it as compatible and hassle-free as possible for unity devs (me included!). This is one of the main aspirations of this project.

If I had to remove the `record` type and `immutable` structures, so be it. It will be a bit risky, so I will add more unit tests to ensure the correctness of the implementation, but overall, these are just "shiny things" the library would still thrive without, anyway.

**Comment by arne-schroppe** [comment]
Well, maybe there is a way, I didn't try very hard to make it work. But I'm not so sure if Unity already supports C# 9, which would be needed for `record` types afaik 🤔

**Comment by Mazyod** [comment]
Finally tested and working on an actual unity project 🎉

**Comment by arne-schroppe** [comment]
> Finally tested and working on an actual unity project 🎉

Nice! 🥳  I'll try this updated version in our project when I find the time, but it could take a few days

**Comment by Mazyod** [comment]
I think this PR dragged on for long enough 😅 .. Will merge it in order to get it into as many users hands as possible. The feedback will hopefully help us reach v1.0 faster.

**Pull request merged**
